### ISSUE TITLE
script can't uninstall compenium app

### ISSUE THREAD

**Issue by LeOS-GSI** [mrrfv/linux-android-backup#17]
app stop working

`? What do you want to do? Backup
Linux Android Backup will install a companion app on your device, which will allow for contacts to be backed up and restored.
The companion app is open-source, and you can see what it's doing under the hood on GitHub.
Downloading companion app.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.2M  100 16.2M    0     0  2505k      0  0:00:06  0:00:06 --:--:-- 3345k
Attempting to uninstall companion app.

companion app isn't showing on Android 12.1 device. When installing manual the companion apk the script showing the same result

**Comment by mrrfv** [comment]
Please comment out the lines 45 and 49 in the script, and share the command output again.

![image](https://user-images.githubusercontent.com/92185687/183482428-7d0878d5-43c8-4798-a88c-5afef7349100.png)

**Comment by LeOS-GSI** [comment]
I'm using now a backup solution which doesn't need a rooted device. so I won't try/use you app anymore. But thanks for fast reply.

**Comment by mrrfv** [comment]
I've just verified this issue on a phone running Android 12 (LineageOS GSI). Reopening.

Logs, if anyone's interested:
```
Companion app already downloaded.
Attempting to uninstall companion app.
Failure [DELETE_FAILED_INTERNAL_ERROR]
```
