### ISSUE TITLE
MIUI and .nomedia files

### ISSUE THREAD

**Issue by uwe-ho** [mrrfv/linux-android-backup#18]
In .../Android/data folders of MIUI exist .nomedia files for which I did not find any way to delete or them or change their permissions. Due to lacking read access 'adb pull' is stopped after running into them and the whole run attempt is over. This way, personally I would write some for loop with additional checks ... (because I couldn't find any adb option to ignore errors for pull; presumably my ignorance, sorry). Thanks.
BTW: MIUI is not so nice concerning permanent install / uninstall, at least not with me. Hence, I installed the apk manually once after copying to phone and removed the (un)installs from the script.

**Comment by mrrfv** [comment]
This is related to issue #15, which has been abandoned by its original author. I'll try to find an alternative way to export the internal storage, as `adb pull` has proven to be very unreliable in my recent tests.

**Comment by mrrfv** [comment]
I just found an alternative way to copy everything off an Android device and it's a thousand times better than `adb pull`, but it'll take a while before this fix gets pushed to master as it'll change the way backed up data are laid out in the archives themselves (unless I find a workaround), potentially causing compatibility issues with older backups or versions of this script. This might be a good time to rename this project.

**Comment by mrrfv** [comment]
Feel free to reopen this issue if you still encounter issues.
