### ISSUE TITLE
tar: unexpected EOF error 

### ISSUE THREAD

**Issue by bruciexx** [mrrfv/linux-android-backup#21]
Heya mrrfv,
I'm having some troubles/bugs with the #Export contacts part of the script
have been trying to fix it myself but I'm kind of struggling.

would love to provide you with more info but I'm not sure what to send

awaiting your reply with excitement <3
Bruce.

**Comment by mrrfv** [comment]
Related to #20.

It seems like some devices don't support the method Linux Android Backup uses to copy data from the device. I'll see if it'd be possible to make the script check if the method is supported and if not, resort to `adb pull`, which works on all devices but is prone to be unstable in my testing. Are you using a Samsung phone?

**Comment by mrrfv** [comment]
Fixed in the latest commit - pick the adb exporting method and the script should backup your phone without issue.
