### ISSUE TITLE
tar Archive base-256 value is out of off_t range during backup / Freeze

### ISSUE THREAD

**Issue by mikedlr** [mrrfv/linux-android-backup#27]
## Device info

Manufacturer: OnePlus 5t
Android version: 18.1
Custom ROM/rooted? Yes - LineageOS
Model:

## System info

Available disk space: 500G
Operating system: Ubuntu 14LTS

---
Running the backup ends up with an error like

    Exporting contacts (as vCard).
     379KiB 0:00:00 [ 529KiB/s] [  <=>                                                                                                                                              ]
    Removing temporary files created by the companion app.
    Exporting internal storage - this will take a while.
    tar: Archive base-256 value is out of off_t range
    tar: Skipping to next header
    tar: Exiting with failure status due to previous errors

and then seems to freeze.

**Comment by mrrfv** [comment]
Use the `adb` export method instead (you are asked for the export method every time you run the script). The `tar` export method doesn't work on all devices, and I can't do anything about it.

**Comment by mikedlr** [comment]
Confirmed. ADB finally worked. .

It would be possible to detect the tar failure and try again with adb. Quite a bit of work though I guess? 

Thanks very much for the script and for helping with this.
