### ISSUE TITLE
backup.sh always fails with"tar: This does not look like a tar archive"

### ISSUE THREAD

**Issue by wolkenkuckuck** [mrrfv/linux-android-backup#29]
Hello,

I have been trying to use your LAB tool since I have read about it in an article of the German LinuxUser magazine ed. 09/2022 pp. 18-22 by Ferdinand Thommes, but so far it always aborts with below error, right after tentative storage of apk files for installed apps.

Is this a known issue with an effective fix or workaround?

Regards,
Ralph

7.56MiB 0:00:01 [7.36MiB/s] [ <=>                                              ]
55.3MiB 0:00:07 [7.57MiB/s] [       <=>                                        ]
6.17MiB 0:00:00 [7.36MiB/s] [<=>                                               ]
2.69MiB 0:00:00 [6.96MiB/s] [<=>                                               ]
 110MiB 0:00:12 [8.59MiB/s] [            <=>                                   ]
1.91MiB 0:00:00 [5.93MiB/s] [<=>                                               ]
3.94MiB 0:00:01 [3.58MiB/s] [ <=>                                              ]
91.0MiB 0:00:10 [8.66MiB/s] [          <=>                                     ]
Exporting contacts (as vCard).
0.00 B 0:00:00 [0.00 B/s] [<=>                                                 ]
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

[fiddle@lenolap:~/LU/202209]
$ ls backup-tmp/Apps/|grep -Ec \[0-9]+\\.apk
128

[fiddle@lenolap:~/LU/202209]
$ du -shx backup-tmp/Apps/
3.4G	backup-tmp/Apps/

[fiddle@lenolap:~/LU/202209]
$ ll backup-tmp/Contacts/
total 0

**Comment by mrrfv** [comment]
It indeed is a known issue with an easy to use workaround. It seems like your computer isn't 100% compatible with the `tar` binary that's on your phone, so you have to pick the `adb` export method when asked by the script. It's very odd that the script was able to export the apps before failing though; do you have any contacts saved on the device, and did you export them with the companion app when asked by the script?

**Comment by wolkenkuckuck** [comment]
Thanks for your reply.
I forgot to mention my devices and their OSes.
The phone I intend to backup is a Galaxy A51 Model No. SM-A515F/DSN with Android 11 with kernel 4.14.113-21582303
but with a pretty dated patch level of May 1st 2021
The backing up device is a Lenovo with Fedora as OS, viz:

[root@lenolap:~]
# echo system-{manufacturer,product-name,version}|xargs -n1 dmidecode -s
LENOVO
80LH
Lenovo B51-35

[root@lenolap:~]
# cat /etc/fedora-release 
Fedora release 35 (Thirty Five)

[root@lenolap:~]
# cat /etc/fedora-release 
Fedora release 35 (Thirty Five)

I do have over 300 contacts in my phone's telephone directory.
Since of its 128 GB built-in storage abt. 80 GB are used I have to backup to an external 2 TB hdd connected via usb because I require twice the amount as the LAB script seems to temporarily store retrieved files copied via adb from the phone beneath backup-tmp dir before creating the zip archive, and my laptop doesn't have that amount of free disk space available anymore.
That's why I mounted these two LVs in the HOME of the user who executes the backup.sh script.

[fiddle@lenolap:~/lab]
$ df -hP . diensthandy/
Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/vg_usb-lv_tmp          127G   38M  121G   1% /home/fiddle/lab
/dev/mapper/vg_usb-lv_diensthandy  127G   28K  121G   1% /home/fiddle/lab/diensthandy


I wasn't asked by the backup.sh script to possibly select the adb export method.

[fiddle@lenolap:~/lab]
$ ./linux-android-backup-latest/backup.sh 
Please enable developer options on your device, connect it to your computer and set it to file transfer mode. Then, press Enter to continue.

If you have connected your device correctly, you should now see a message asking for access to your phone. Allow it, then press Enter to go to the last step.
Tip: If this is not the first time you're using this script, you might not need to allow anything.

List of devices attached
R58N4157BHR	device

Can you see your device in the list above, and does it say 'device' next to it? If not, quit this script (ctrl+c) and try again.
? What do you want to do? Backup
Linux Android Backup will install a companion app on your device, which will allow for contacts to be backed up and restored.
The companion app is open-source, and you can see what it's doing under the hood on GitHub.
Companion app already downloaded.
Attempting to uninstall companion app.
Installing companion app.
Performing Streamed Install
Success
Granting required permissions to companion app.
Cleaning up after previous backup/restore...
removed 'backup-tmp/Apps/base.apk'
removed directory 'backup-tmp/Apps'
removed directory 'backup-tmp'
Note: Backups will first be made on the drive this script is located in, and then will be copied to the specified location.
[fiddle@lenolap:~/lab]
$ ./linux-android-backup-latest/backup.sh 
Please enable developer options on your device, connect it to your computer and set it to file transfer mode. Then, press Enter to continue.

If you have connected your device correctly, you should now see a message asking for access to your phone. Allow it, then press Enter to go to the last step.
Tip: If this is not the first time you're using this script, you might not need to allow anything.

List of devices attached
R58N4157BHR	device

Can you see your device in the list above, and does it say 'device' next to it? If not, quit this script (ctrl+c) and try again.
? What do you want to do? Backup
Linux Android Backup will install a companion app on your device, which will allow for contacts to be backed up and restored.
The companion app is open-source, and you can see what it's doing under the hood on GitHub.
Companion app already downloaded.
Attempting to uninstall companion app.
Installing companion app.
Performing Streamed Install
Success
Granting required permissions to companion app.
Cleaning up after previous backup/restore...
removed 'backup-tmp/Apps/base.apk'
removed directory 'backup-tmp/Apps'
removed directory 'backup-tmp'
Note: Backups will first be made on the drive this script is located in, and then will be copied to the specified location.
? Please enter the backup location. Enter '.' for the current working directory. diensthandy
Starting: Intent { cmp=com.example.companion_app/.MainActivity }
The companion app has been opened on your device. Please press the 'Export Data' button - this will export contacts to the internal storage, allowing this script to backup them. Press Enter to continue.


Here the LAB Companion App popped up on my phone's display where I pressed the "Export Data" button
and allowed the app access to all files.
Then the app replied "Data Exported - Please continue the backup process on your computer"
And on my backup laptop I hit enter

**Comment by wolkenkuckuck** [comment]
@mrrfv thank you for your reply.
I think my issue was that the external usb hdd where I wanted my phone backup to be written to spinned down after a certain period of assumed inactivity.
Unfortunately, as this is a cheap device, it couldn't be prevented from doing so by sdparms with an e.g. --clear=STANDBY.
But what helped was a cronjob that touched a partition of the device every 5 minutes.
Because of the great amount of data on my phone the backup ran all night.

[fiddle@lenolap:~/lab]
$ sudo crontab -l
*/5 * * * * bash -c '{ lsblk -no name /dev/sdb3 && touch /dev/sdb3; } &>/dev/null'

[fiddle@lenolap:~]
$ df -hP ~fiddle/lab/ ~fiddle/lab/diensthandy/
Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/vg_usb-lv_tmp          127G   25M  121G   1% /home/fiddle/lab
/dev/mapper/vg_usb-lv_diensthandy  127G   46G   75G  39% /home/fiddle/lab/diensthandy

[fiddle@lenolap:~]
$ ls -lh /home/fiddle/lab/diensthandy
total 46G
-rw-rw-r--. 1 fiddle fiddle 46G Oct 10 08:58 linux-android-backup-10-10-2022-02-35-32.7z
drwx------. 2 root   root   16K Oct  3 21:55 lost+found


tail of backup.sh output:

emoving backup-tmp/Storage/Schedule          
Removing backup-tmp/Storage/Podcasts           
Removing backup-tmp/Storage/Ringtones          
Removing backup-tmp/Apps                        
Removing backup-tmp/Contacts       
Removing backup-tmp/Storage            
                                      
Everything is Ok
Backed up successfully.
If this project helped you, please star the GitHub repository. It lets me know that there are people using this script and I should continue working on it.
