### ISSUE TITLE
Feature request: backing up Wi-Fi networks' passwords

### ISSUE THREAD

**Issue by Gray47Maxx** [mrrfv/linux-android-backup#31]
The title basically is self-explanatory. Might be a simple wlan_pw.txt or smth more useful.

**Comment by mrrfv** [comment]
This would be only possible on rooted devices, and the main selling point of Linux Android Backup is that it doesn't require root to function. It's not a bad idea though - I think it'd be awesome to add some kind of "hook" or "extension" system, where users can include their own backup steps (including this one).

**Comment by upintheairsheep** [comment]
requires root
