### ISSUE TITLE
script aborts if an apk is missing

### ISSUE THREAD

**Issue by schymans** [mrrfv/linux-android-backup#42]
## Device info
Manufacturer: Sony
Android version: 7.1.1
Custom ROM/rooted? no
Model: Sony Xperia Z5 compact (suzuran)

## System info
Debian bullseye
Available disk space:
Operating system:

---
Something is going wrong with the apk download, causing the whole script to crash. I get:
```
Attempting to uninstall companion app.
Exporting apps.
adb: error: remote object '/mnt/asec/de.alpstein.alpregio.SchweizerPaerke-1/base.apk' does not exist
```
This app does not feature in my list of apps, so it is some artefact from a previous installation. Can I make the script just ignore such apps?

**Comment by mrrfv** [comment]
Directly related to issue #44.

**Comment by mrrfv** [comment]
Fixed in the latest commit.
