### ISSUE TITLE
Store apks using their original package names

### ISSUE THREAD

**Issue by thelazyoxymoron** [mrrfv/linux-android-backup#47]
I had recently backed up my android device using the tool, however I noticed that all the apks were backed up using a random identifier. This made it harder to selectively install applications. It would be preferred if we backup using their original package names.

**Comment by thelazyoxymoron** [comment]
If uniqueness was the issue, maybe we can add random numbers at the end of the package name?

**Comment by mrrfv** [comment]
Done, thanks for reporting.
