### ISSUE TITLE
empty name of .apk

### ISSUE THREAD

**Issue by spikyatlinux** [mrrfv/linux-android-backup#5]
Hey nice work, but perhaps you could change
 line 96 `(cd $output && adb pull $( echo $app | sed "s/package://" | sed "s/.apk=/.apk /" | sed "s/\([[:blank:]]\).*/\1/" ).apk)` produce an empty filename.apk `.apk` if you change it to `(cd $output && adb pull $( echo $app | sed "s/^package://" | sed "s/base.apk=/base.apk /" | sed 's/\r//g').apk)` you´ll get the right name if you wish that.

Best reagrds

**Comment by Poomex** [comment]
It would be nice if the apk files had appropriate names in the archive. Same with contacts.

**Comment by mrrfv** [comment]
Commit f8568ea5af728b255e9129ea15caa07448e64256 fixes this issue.
