### ISSUE TITLE
Please add "Doesn't save MMS attachments" to the readme

### ISSUE THREAD

**Issue by RanTalbott** [mrrfv/linux-android-backup#58]
## Device info

Manufacturer: Samsung
Android version: 9
Custom ROM/rooted? No
Model: J7

## System info

Available disk space: 14320128K
Operating system: Ubuntu 20.04

---

**Describe the issue below.**
Great job, and I starred the project because it created a backup I **wished** I'd had when my old phone went for an unplanned swim :-(

But ... it just so happened that, at the moment, I had received some texts with **dozens** of attached JPEGs from a friend, and was hoping for a backup that would simplify extracting them to my PC.

I understand that saving attachments in a way that associates them with the text would be a hassle, and restoring them could be a nightmare if the internal formats varied across Android versions, so I'm not making a feature request. But please do update the documentation so users won't be unpleasantly surprised if they find they **need.** their backup.

Thanks,

Ran

p.s. I did find a free app on the Play Store that saves text threads as HTML files, and embeds JPEGs (dunno yet whether it works on other media) in base64. It doesn't restore, though (probably because that nightmare I feared is real). I'm gonna write a python program that will extract the pics and name them so they're associated with the threads. If it's okay with you, I'll add a comment with referrals if it works out (don't want to do unwelcome promotions).

**Comment by mrrfv** [comment]
Thanks for starring the project and letting me know about your experience. I've updated the README to clarify that the script only backs up SMS messages with no MMS media.
