### ISSUE TITLE
location to backup data & encryption

### ISSUE THREAD

**Issue by Zackaryia** [mrrfv/linux-android-backup#9]
Most people will have external drives that are where theyre data will lie, so it would be nice to be able to set that as the abckup location. 

Also setting optional encryption is very nice because not everyone wants encryption, and many may even need to have it **disabled**.

Also if you type in an encryption password incorrectly it ends the whole backup process, effectively wasting your 2 hours of backing up your phone.

**Comment by mrrfv** [comment]
Support for custom backup locations has been added in bb444893a4b77ca58768b97900e229a6dc63901a - `git pull` or redownload to update. As this script is mainly geared towards geeks and privacy-oriented users (for now), making encryption optional is currently not an option (and I think it's very dangerous to disable it, your phone encrypts all data by default for a reason).

> if you type in an encryption password incorrectly it ends the whole backup process

As a workaround, you can provide the password to the script *once* as an environment variable. For example:

```bash
archive_password="very strong password here" ./backup.sh
```

See [Automation/Unattended Backups](https://github.com/mrrfv/linux-android-backup#automationunattended-backups) for details.
